//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Unit
    {
        public string Product_Code { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Sell_Price { get; set; }
        public Nullable<decimal> Original_Price { get; set; }
        public string Base_Product_Code { get; set; }
        public Nullable<int> QuantityPerUnit { get; set; }
    }
}
