//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Product_Category_ID { get; set; }
        public Nullable<int> Base_Unit_ID { get; set; }
        public Nullable<int> Min_Quota { get; set; }
        public Nullable<int> Max_Quota { get; set; }
    }
}
