//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Image
    {
        public long ID { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
