//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string code { get; set; }
        public string Type { get; set; }
        public Nullable<int> Type_Group_ID { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
        public string Created_User { get; set; }
        public Nullable<long> Partner_ID { get; set; }
        public Nullable<long> Shop_ID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Note { get; set; }
    }
}
